### ISSUE TITLE
Zendrive fatal error caused by SQLiteDatabaseLockedException

### ISSUE THREAD

**Issue by vikramezhil** [zendrive/zendrive-sdk-android-sample#27]
We are getting random crashes in our app which uses Zendrive and upon further investigation from our side we noticed this was caused by incorrect sqlite write process.

This error usually occurs when a sqlite database is not closed after writing data or multiple number of threads are accessing the database at a single give instance. Please do note, other than zendrive there is no instance of the app accessing the sqlite database.

Below is the crash report, please let us know if you would need further information from our end to resolve this issue.

**Zendrive SDK Version** - 5.8.0

> Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
#################################################################
Error Code : 5 (SQLITE_BUSY)
Caused By : The database file is locked.
	(database is locked (code 5): , while compiling: PRAGMA journal_mode)
#################################################################
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
       at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:762)
       at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:443)
       at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:417)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:315)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:210)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:908)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:878)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:699)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:637)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:283)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.zendrive.sdk.i.s.<init>(s:184)
       at com.zendrive.sdk.i.s.b(s:124)
       at com.zendrive.sdk.i.s.a(s:98)
       at com.zendrive.sdk.i.bj.<init>(s:99)
       at com.zendrive.sdk.i.bj.h(s:113)
       at com.zendrive.sdk.i.bm.i(s:84)
       at com.zendrive.sdk.i.bm.a(s:10331)
       at com.zendrive.sdk.i.bm$1.aW(s:109)
       at com.zendrive.sdk.i.bm$8.run(s:907)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by zendrive-developers** [comment]
Can you please report this at support@zendrive.com and we will look into it?

**Comment by vikramezhil** [comment]
@zendrive-developers Thank you for the update, we have sent an email to your support team with the issue details.
